//#pragma enable_d3d11_debug_symbols
#pragma kernel CSMain

float4 color;
Texture2D<float4> baseImage;
Texture2D<float4> image;
RWStructuredBuffer<uint> result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID) {
    float3 c = abs(baseImage[id.xy].rgb - color.rgb);

    if (all(baseImage[id.xy] == image[id.xy])) {
        InterlockedAdd(result[0], 1);
    }

    if (all(c <= float3(0.005, 0.005, 0.005))) {
        InterlockedAdd(result[1], 1);
    }
}
